name: Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request: 
    branches:
      - main
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando o repositorio e trocando para a branch correta
        uses: actions/checkout@v4

      - name: Instalando o Node.js versão 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Instalando dependencias
        run: npm ci

      - name: Rodar testes de cobertura
        run: npm run coverage
    
  test-integration:
      runs-on: ubuntu-latest
      steps:
        - name: Clonando o repositorio e trocando para a branch correta
          uses: actions/checkout@v4

        - name: Instalando o Node.js versão 22.x
          uses: actions/setup-node@v4
          with:
            node-version: 22.x
            cache: 'npm'

        - name: Instalando dependencias
          run: npm ci

        - name: Rodar testes unitarios
          run: npm run test:integration

  test-2e2:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando o repositorio e trocando para a branch correta
        uses: actions/checkout@v4

      - name: Instalando o Node.js versão 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Instalando dependencias
        run: npm ci

      - name: Rodar testes end-to-end
        run: npm run test:e2e
